# Generated by Django 4.0.3 on 2022-03-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_plan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plan'),
        ),
    ]
